"use client";

import { ColorSchemeScript, MantineProvider, createTheme } from "@mantine/core";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>My awesome app</title>
        <ColorSchemeScript />
      </head>
      <body>
        <main className="min-h-screen bg-background flex flex-col items-center">
          <MantineProvider theme={theme}>{children}</MantineProvider>
        </main>
      </body>
    </html>
  );
}
